[project]
name = "ynb-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-ydoc>=3.0.3",
    "mcp[cli]>=1.6.0",
]
